stages:
  - mirror
  - buildwin

Mirror to gh:
  stage: mirror
  image: haffmans/git-mirror:latest
  script:
  - git-mirror "${CI_PROJECT_DIR}" git@github.com:${GITHUB_REPOSITORY}


Build Windows:
  stage: buildwin
  image: registry.gitlab.com/nickdonnelly/horus/aws-deploy-horus:windows

  script:
  - x86-64-w64-mingw32-qmake-qt5 horusqt.pro
  - make -j7
  - ls release
