stages:
    - mirror

Mirror to gh:
  stage: mirror
  image: haffmans/git-mirror:latest
  script:
  - echo 'ENV Variables'
  - echo 'CI_PROJECT_DIR ${CI_PROJECT_DIR}'
  - echo 'GITHUB_REPOSITORY ${GITHUB_REPOSITORY}'
  - git-mirror "${CI_PROJECT_DIR}" git@github.com:${GITHUB_REPOSITORY}