stages:
  - mirror
  - buildwin
  - buildlinux

Mirror to gh:
  stage: mirror
  image: registry.gitlab.com/nickdonnelly/horus/git-mirror:latest
  script:
  - git-mirror "${CI_PROJECT_DIR}" git@github.com:${GITHUB_REPOSITORY}


Build Windows:
  stage: buildwin
  image: registry.gitlab.com/nickdonnelly/horus/aws-deploy-hours:windows
  only:
  - master
  - staging

  script:
  - i686-w64-mingw32.static-qmake-qt5 horus.pro
  - make -j7
  - cd release
  - rm *.o *.h *.cpp
  - cd ..

  artifacts: # save the file 
    paths:
    - release/horusqt.exe
    expire_in: 1 week
  

Build Linux:
  stage: buildlinux
  image: rabits/qt:5.10-desktop
  only:
  - master
  - staging

  script:
  - sudo apt-get -qq update
  - mkdir build && cd build
  - qmake -r ../
  - make -j4

  artifacts:
    paths:
    - build/*
    expire_in: 1 week
