stages:
  - mirror
  - buildwin
  - buildlinux

Mirror to gh:
  stage: mirror
  image: registry.gitlab.com/nickdonnelly/horus/git-mirror:latest
  script:
  - git-mirror "${CI_PROJECT_DIR}" git@github.com:${GITHUB_REPOSITORY}


Build Windows:
  stage: buildwin
  image: haffmans/mingw-qt5:latest
  only:
  - master
  - staging

  script:
  - x86_64-w64-mingw32-qmake-qt5 horus.pro
  - make -j7

  artifacts: # save the file 
    paths:
    - build/*
    expire_in: 1 week
  

Build Linux:
  stage: buildlinux
  image: rabits/qt:5.10-desktop
  only:
  - master
  - staging

  script:
  - export QMAKE_CXXFLAGS="-std=c++14"
  - sudo apt-get -qq update
  - qmake horus.pro 
  - make -j4

  artifacts:
    paths:
    - build/*
    expire_in: 1 week
